development:
  adapter: postgresql
  encoding: unicode
  database: bookfy_development
  pool: 5
  username: brunochagas
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: bookfy_test
  pool: 5
  username: brunochagas
  password:

production:
  adapter: brunochagas
  encoding: unicode
  database: bookfy_production
  pool: 5
  username: bookfy
  password:
